# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://zhoujump.github.io/site.io/
date_format: "ordinal"
title: 粥酱的小站
subtitle: "时不时分享一些小想法"
description: "title: 粥酱的小站"
keywords: 粥粥粥菌
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: ZhouJump
organization: 
organization_url: 
github_username: ZhouJump
location: hunan, China
email: zhoujump@126.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档


  -
    href: /links/
    label: 友情链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: https://zhoujump.github.io/site.io/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: ZhouJump
    repo: talk
    oauth:
        client_id: c6df924e43ae3e9169e3
        client_secret: 7cb69c27e1fd4f2a4582836f60e1bf37304929d9
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: ZhouJump
    repo: gitalk-comment
    clientID: c6df924e43ae3e9169e3
    clientSecret: 7cb69c27e1fd4f2a4582836f60e1bf37304929d9
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
